try {
    throwException(data)
} catch (e: Exception) {
    handleException(data)
}